spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/dhairya
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.jpa.hibernate.ddl-auto=none
fast2sms.api.key=${FAST2SMS_API_KEY}