spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/dhairya
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=none